lib/rbeapi/eapilib.rb

Before:
[1] pry(main)> require 'rbeapi/client'
=> true
[2] pry(main)> node = Rbeapi::Client.connect_to('switch-001')
NameError: uninitialized constant Rbeapi::Eapilib::HttpsEapiConnection::OpenSSL
from /Users/brandt/.cache/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rbeapi-0.1.0/lib/rbeapi/eapilib.rb:325:in `initialize'
After:
[1] pry(main)> require 'rbeapi/client'
=> true
[2] pry(main)> node = Rbeapi::Client.connect_to('switch-001')
=> #<Rbeapi::Client::Node:0x007fb2e4ba2d10
@autorefresh=true,
@connection=
#<Rbeapi::Eapilib::HttpsEapiConnection:0x007fb2e4ba2dd8
@error=nil,
...

Fix missing OpenSSL require

---

README.md

- Fixed a couple typos in code examples.
- Merged a few line breaks in code.
- Chomp trailing newlines at end of doc.

Fix a couple typos, minor formatting in README.md

---

.gitignore
README.md
Rakefile
gems/README.rst
gems/inifile/.gitignore
gems/inifile/README.rst
gems/inifile/inifile.spec.tmpl
gems/net_http_unix/.gitignore
gems/net_http_unix/README.rst
gems/net_http_unix/net_http_unix.spec.tmpl
rbeapi.spec.tmpl

This includes packaging for net_http_unix and inifile rubygems ONLY to be used within an EOS swix.  Will generate an RPM for Ruby... open source (barename) and for the Ruby... provided with the pe-puppet extension (prefixed with pe-).

Feature - generate RPMs and instructions for SWIX files

---

lib/rbeapi/client.rb
lib/rbeapi/eapilib.rb

Added option about HTTP read_timeout to 'enable'.
It's useful for commands that takes HTTP response over 10 seconds. (e.x. copy EOS file from server.)
Will work as below.
```ruby
node.enable('copy tftp://192.168.101.1/EOS-4.15.0F.swi flash:EOS-4.15.0F.swi', open_timeout: 10, read_timeout: 600)
```
it's optional parameter, so will work as below. (default 10 sec)
```ruby
node.enable('show version')
```

add HTTP read_timeout

---

Rakefile
gems/inifile/inifile.spec.tmpl
gems/net_http_unix/net_http_unix.spec.tmpl
rbeapi.spec.tmpl

- Ubuntu 12 uses an older version of awk that does not support the -e
option.
- Ubuntu rpmbuild does not auto-create the buildroot dir.
- Enhance final output from each RPM buld step in the Rakefile.

Fix RPM packaging for Ubuntu systems. Fixes #11

---

lib/rbeapi/api/interfaces.rb
spec/unit/rbeapi/api/interfaces/fixture_interfaces.text
spec/unit/rbeapi/api/interfaces/portchannel_spec.rb

- Regex now anchors on a word-boundary
- Added 2 unit tests
- Fixup existing port-channel tests by mocking 'show port-channel <n>
all-ports'

Fixes #16 - Change port-channel members regex to anchor on word-boundary.

---

README.md
lib/rbeapi/client.rb
lib/rbeapi/eapilib.rb

Allows setting default timeout values in eapi.conf.

Add read_timeout and open_timeout to client.rb Issue 10

---

lib/rbeapi/client.rb

Thank you for add `[connection:*]` to eapi.conf syntax.
But now, if `[connection:*]` section is used,   `connect` method called with `"host"=>"*"` .
This PR fix it.
see. #18

name path through if default connection is used

---

lib/rbeapi/client.rb

Added `dry_run` boolean attribute to `Rbeapi::Client::Node` .
If `Node.dry_run` is `true` , `Node.config` DO NOT executes eAPI request to device and only print stdout `[rbeapi dry-run commands]` and `commands` .
(`Node.enable` , `Node.get_config` and so on are not affected.)
Will work as below.
```ruby
require 'rbeapi/client'
node = Rbeapi::Client.connect_to('vEOS-spine001')
node.dry_run = true
hash_vlans = node.enable('show vlan')[0][:result]["vlans"] rescue nil
p hash_vlans
hash_vlans.each_key do |vlan|
next if (vlan.to_i == 1 || vlan.to_i == 4094)
node.config([
"interface Po1",
" switchport trunk allowed vlan add #{vlan}"
])
end
```
Results in as below.
```bash
[kotetsu@centos66-ruby 201507_rbeapi_test_dryrun]$ ruby rbeapi_test_dryrun.rb
{"1"=>{"status"=>"active", "name"=>"default", …
```

add dry-run mode

---

lib/rbeapi/api/users.rb

Ensure nil is returned when you try to get nonexistent username. Ran into this issue while creating user system tests.

Ensure that nil is returned when you try to get nonexistent username.

---

spec/system/rbeapi/api/routemaps_spec.rb

Routemaps that exist on the switch before test was run will be returned by getall.
There is no easy way to clear out all the routemaps and didn't want to loop on the
entries not created by test and delete them.

Relax check on getall entries

---

lib/rbeapi/api/dns.rb
lib/rbeapi/api/logging.rb
lib/rbeapi/api/ntp.rb
lib/rbeapi/api/system.rb

Noticed a few parse methods that weren't private while updating documentation.

Ensure all parse methods are private.

---

lib/rbeapi/client.rb
lib/rbeapi/utils.rb
spec/fixtures/eapi.conf.yaml
spec/fixtures/env_path.conf
spec/system/rbeapi/client_spec.rb
spec/unit/rbeapi/client_spec.rb

Created utils method to syslog warning messages.
Updated add_connection to return nil instead of returning connection values.
Updated tests to deal with add_connection return value change.
Added test case for bad conf file and empty conf file.
Added test case to verify EAPI_CONF path is used.
Fixes issue #82

Catch errors and syslog them when parsing eapi conf file.

---

Gemfile

Rubocop > 0.37 requires a gem that only works with ruby 2.x

Limit rubocop version when running ruby 1.9

---

lib/rbeapi/api/interfaces.rb
spec/system/rbeapi/api/interfaces_ethernet_spec.rb
spec/unit/rbeapi/api/interfaces/ethernet_spec.rb

* Changes the behaviour of the speed functions (parse_speed and set_speed). Before the speed setting could not be applied to an ethernet interface.
* Adds support of lacp port-priority for ethernet interfaces
* (replaces pull request https://github.com/arista-eosplus/rbeapi/pull/138)

fix speed functions and add lacp port-priority functions

---

lib/rbeapi/api/switchports.rb
spec/system/rbeapi/api/switchports_spec.rb
spec/unit/rbeapi/api/switchports/default_spec.rb

* Adds switchport allowed vlan range capability. Allowed vlans will be returned as they appear in the eos and can be configured in the same way as in the eos: (old: 5,6,7,9,10,15 new: 5-7,9-10,15)
* The allowed vlans array changed from int to string because a vlan range could be returned and set

add switchport allowed vlan range capability

---

Gemfile
lib/rbeapi/api/interfaces.rb

- Sort portchannel members list for consistent comparisons.
- Restrict json rubygems version when testing with Ruby 1.9.

Fix test issues

---

lib/rbeapi/api/interfaces.rb
spec/system/rbeapi/api/interfaces_base_spec.rb

This fixes the issue #142 by excluding the `multicast-group decap` line so the multicast group is '' when not configured.
An additional test has been added for parsing the multicast group when set.

fix issue #142 - multicast group parsing when not configured

---

lib/rbeapi/api/stp.rb
spec/system/rbeapi/api/stp_instances_spec.rb

This fixes the parse_instances function to always return the MST instances 0 and 1 because their priority is defined by default in EOS. The MST instance 0 never shows up in the config section "spanning-tree mst configuration" and the MST instance 1 can show up if configured so. 
Some additional tests are added to test the default mst instances and their priorities.
Example config which would can't be parsed without this fix:
`switch#show run all | s spanning-tree mst`
`spanning-tree mode mstp`
`no spanning-tree mst pvst border`
`spanning-tree mst 0 priority 8192`
`spanning-tree mst 1 priority 32768`
`!`
`spanning-tree mst configuration`
`   no name`
`   revision 0`
`switch#`

fix parse_instances to return the default instances and add tests

---

lib/rbeapi/client.rb
spec/unit/rbeapi/client_spec.rb

- Fixes #127.  Returns nil when the requested config does not exist.
- An empty config will return an empty string ('').
- Any other command error will raise CommandError.

Ensure get_config, running_config, and startup_config return sane output

---

lib/rbeapi/api/prefixlists.rb
spec/system/rbeapi/api/prefixlists_spec.rb
spec/unit/rbeapi/api/prefixlists/default_spec.rb
spec/unit/rbeapi/api/prefixlists/fixture_prefixlists.text

- update 'get' and 'getall' to be able to handle multi/single-line
- add single-line prefix list to unit test fixture
- update system spec tests to use also single-line

add support for multi/single-line prefix list output

---

lib/rbeapi/api/interfaces.rb
spec/system/rbeapi/api/interfaces_vlan_spec.rb
spec/unit/rbeapi/api/interfaces/fixture_interfaces.text
spec/unit/rbeapi/api/interfaces/vlan_spec.rb

This patch implements the autostate function for vlans, which is necessary for e.g. MLAG configuration.

added support for autostate

---

lib/rbeapi/api/ntp.rb
spec/system/rbeapi/api/ntp_spec.rb

This commit enhances the existing ntp_config and ntp_server methods
and adds ntp_auth_key per changes in puppetlabs/netdev_stdlib#21
ntp_config
- authenticate
- trusted_key
ntp_server
- key
- maxpoll
- minpoll
- source_interface
- vrf
ntp_auth_key
- key
- algorithm
- mode
- password

(NETDEV-29) Enhance netdev NTP api
