arista-eosplus/rbeapi

- lib/rbeapi/client.rb
Fixed spelling errors in comments.
> Set host key to connection profile name if host key not set. ISSUE 6

- Gemfile
- lib/rbeapi/api/acl.rb
- rbeapi.gemspec
- spec/system/api_acl_spec.rb
- spec/unit/rbeapi/api/acl/default_spec.rb
- spec/unit/rbeapi/api/acl/fixture_acl_standard.text
Added netaddr gem as a runtime dependency.
> Added API for standard ACLs with unit and system test.

- lib/rbeapi/api/acl.rb
Hash key names were changed to match the ruby class.
There is no rule that they have to be the same but there was no good
reason for them to be different in this case.
> Change class name and hash key names.

- Rakefile
- gems/inifile/inifile.spec.tmpl
- gems/netaddr/README.rst
- gems/netaddr/netaddr.spec.tmpl
> Add netaddr rubygem rpm

- lib/rbeapi/api/users.rb
- spec/unit/rbeapi/api/users/default_spec.rb
Updates for puppet users integration test
> Feature user updates

- lib/rbeapi/api/interfaces.rb
> Correct option to request 'text' results

- Rakefile
- rbeapi.spec.tmpl
Fix some rubocop findings, a typo, and add a task to generate SWIX files.
> Feature puppet4 swix

- spec/fixtures/test.conf
- spec/system/rbeapi/client_spec.rb
- spec/unit/rbeapi/client/default_spec.rb
> Add basic framework tests.

- lib/rbeapi/api/switchports.rb
- spec/system/rbeapi/api/switchports_spec.rb
> Added support for trunk groups.

- lib/rbeapi/api/interfaces.rb
- spec/system/rbeapi/api/interfaces_portchannel_spec.rb
> Add lacp_mode option when setting port-channel members.

- lib/rbeapi/eapilib.rb
- spec/system/rbeapi/client_spec.rb
- spec/unit/rbeapi/client_spec.rb
> test timeout values

- lib/rbeapi/client.rb
- spec/system/rbeapi/client_spec.rb
> Set enable password for a connection.

- lib/rbeapi/client.rb
- spec/fixtures/wildcard.conf
- spec/unit/rbeapi/client_spec.rb
> Copy configuration entry before modifying with connection specific info.

- lib/rbeapi/api/system.rb
- lib/rbeapi/client.rb
- spec/system/rbeapi/api/system_spec.rb
- spec/unit/rbeapi/api/system/default_spec.rb
- spec/unit/rbeapi/api/system/fixture_system.text
> Added support for setting system banners.

- lib/rbeapi/client.rb
- spec/fixtures/test.conf
- spec/unit/rbeapi/client_spec.rb
> Add support for DEFAULT section to eapi config file.

- lib/rbeapi/api/vlans.rb
- spec/system/rbeapi/api/vlans_spec.rb
- spec/unit/rbeapi/api/vlans/default_spec.rb
- spec/unit/rbeapi/api/vlans/fixture_vlans.text
> Only first trunk group was being returned.

- lib/rbeapi/api/dns.rb
- lib/rbeapi/api/interfaces.rb
- lib/rbeapi/api/ipinterfaces.rb
- lib/rbeapi/api/routemaps.rb
- lib/rbeapi/api/switchports.rb
- lib/rbeapi/api/users.rb
- lib/rbeapi/api/varp.rb
- lib/rbeapi/api/vrrp.rb
- spec/system/rbeapi/api/ipinterfaces_spec.rb
- spec/unit/rbeapi/api/interfaces/portchannel_spec.rb
- spec/unit/rbeapi/api/routemaps/default_spec.rb
- spec/unit/rbeapi/api/vrrp/default_spec.rb
> Validate array param options

- lib/rbeapi/api/interfaces.rb
- lib/rbeapi/api/ipinterfaces.rb
- spec/system/rbeapi/api/interfaces_base_spec.rb
- spec/system/rbeapi/api/interfaces_ethernet_spec.rb
- spec/system/rbeapi/api/interfaces_portchannel_spec.rb
- spec/system/rbeapi/api/interfaces_vxlan_spec.rb
- spec/system/rbeapi/api/ipinterfaces_spec.rb
- spec/unit/rbeapi/api/interfaces/base_spec.rb
- spec/unit/rbeapi/api/interfaces/ethernet_spec.rb
- spec/unit/rbeapi/api/interfaces/portchannel_spec.rb
- spec/unit/rbeapi/api/interfaces/vxlan_spec.rb
This pull request includes methods to set/modify load_interval on ethernet interfaces, portchannel interfaces and ip interfaces.
> Wip load interval v2

- Rakefile
- gems/inifile/inifile.spec.tmpl
- gems/net_http_unix/net_http_unix.spec.tmpl
- gems/netaddr/netaddr.spec.tmpl
- lib/rbeapi/switchconfig.rb
- lib/rbeapi/version.rb
- rbeapi.spec.tmpl
Avoid issues later if a user supplies a config with empty lines
> Switchconfig zap empty lines

- lib/rbeapi/api/prefixlists.rb
- spec/system/rbeapi/api/prefixlists_spec.rb
- spec/unit/rbeapi/api/prefixlists/default_spec.rb
- spec/unit/rbeapi/api/prefixlists/fixture_prefixlists.text
- new unit and systems tests for prefix lists
- prefixlists documentation update
- fix prefix list key to 'prefix'
> add spec tests for prefix lists

- lib/rbeapi/api/ospf.rb
- spec/system/rbeapi/api/ospf_interfaces_spec.rb
- spec/system/rbeapi/api/ospf_spec.rb
* add additional ospf instance settings
* max_lsa
* maximum_paths
* passive_interface_default
* passive_interfaces
* active_interfaces
* change return parameters from string to symbol
* fix get interfaces function
* fix set redistribution function
> extend and fix ospf features

- lib/rbeapi/api/managementdefaults.rb
- spec/system/rbeapi/api/managementdefaults_spec.rb
- spec/system/rbeapi/api/users_spec.rb
- spec/unit/rbeapi/api/managementdefaults/default_spec.rb
added support for setting the crypto in managementdefaults
> added support for setting the crypto in managementdefaults

- lib/rbeapi/api/interfaces.rb
- lib/rbeapi/api/switchports.rb
- spec/spec_helper.rb
- spec/system/rbeapi/api/interfaces_base_spec.rb
- spec/system/rbeapi/api/interfaces_ethernet_spec.rb
- spec/system/rbeapi/api/interfaces_portchannel_spec.rb
- spec/system/rbeapi/api/interfaces_vxlan_spec.rb
- spec/unit/rbeapi/api/interfaces/base_spec.rb
- spec/unit/rbeapi/api/interfaces/ethernet_spec.rb
- spec/unit/rbeapi/api/interfaces/portchannel_spec.rb
- spec/unit/rbeapi/api/interfaces/vxlan_spec.rb
add subinterface functionality
> add subinterface functionality

- lib/rbeapi/api/alias.rb
- spec/system/rbeapi/api/alias_spec.rb
- spec/unit/rbeapi/api/alias/default_spec.rb
- spec/unit/rbeapi/api/alias/fixture_alias.text
> add support to set aliase

- .rubocop.yml
- CHANGELOG.md
- README.md
- Rakefile
- lib/rbeapi/api/iphosts.rb
- lib/rbeapi/api/ntp.rb
- lib/rbeapi/api/snmp.rb
- lib/rbeapi/api/system.rb
- lib/rbeapi/version.rb
- spec/support/fixtures.rb
- spec/system/rbeapi/api/iphost_spec.rb
- spec/system/rbeapi/api/managementdefaults_spec.rb
- spec/system/rbeapi/api/ntp_spec.rb
- spec/system/rbeapi/api/staticroutes_spec.rb
- spec/system/rbeapi/api/system_spec.rb
- spec/system/rbeapi/api/users_spec.rb
- spec/system/rbeapi/api/varp_spec.rb
- spec/system/rbeapi/client_spec.rb
- spec/unit/rbeapi/api/iphost/default_spec.rb
- spec/unit/rbeapi/api/iphost/fixture_iphosts.text
- spec/unit/rbeapi/api/system/default_spec.rb
- spec/unit/rbeapi/api/system/fixture_system.text
- Add ip host feature
- Add timezone feature
- Enhance NTP API
> Release 1.2.0

- lib/rbeapi/api/logging.rb
- lib/rbeapi/api/radius.rb
- lib/rbeapi/api/tacacs.rb
https://tickets.puppetlabs.com/browse/NETDEV-30
Closes arista-eosplus/puppet-netdev#41
Closes #173
> (NETDEV-30) Support new properties in Types
